cmake_minimum_required(VERSION 3.8)
project(qianli_sim)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch config worlds rviz DESTINATION share/${PROJECT_NAME})
install(PROGRAMS scripts/ideal_kinematic_sim.py scripts/check_system.py scripts/check_imu_motion.py DESTINATION lib/${PROJECT_NAME})
install(FILES README.md DESTINATION share/${PROJECT_NAME})
ament_package()
